nothrow support and don't write empty class for TypeKind.Namespace modules
DelegWriter:
* Separate out return value declarations from call and put them in preCall, so that try/catch does not break things
* generate: Add try/catch to invoke gidInvokeCallbackExceptionHandler
* Add nothrow to C thunk

Enumeration.constructEnumException: Add nothrow to enum Exception methods
FuncWriter: Add nothrow to declaration if !throws
Func.constructException: Add nothrow to Exception methods
Property.checkGetter/checkSetter: Ensure property method candidates !throws

Repo:
* Add nothrow to IfaceProxy methods
* Add nothrow to C function pointers

SignalWriter:
* Separate out callback return value variable declaration from call, so try/catch doesn't break
* Add nothrow to signal connect template and C thunk
* Surround D delegate call in try/catch and gidInvokeCallbackExceptionHandler

Structure:
* Don't output docs or class for TypeKind.Namespace
* writeInitCode: Add nothrow to constructors, destructors, _cPtr, _getGType, _gType, boxCopy, and builder() methods
* Improve handling of null C instances passed to constructors (silence is golden)
* writeBoxedCtor: Add nothrow
* constructFieldProps: Add nothrow
* constructProps: Add nothrow
* writeBuilder: Add nothrow